title: Cory Poston
theme: jekyll-theme-minimal
# Site settings
title: My Awesome Site
description: >-
  Welcome to my GitHub Pages site! This site is built with Jekyll.
baseurl: ""  # Leave empty if publishing at username.github.io, otherwise set to "/repo-name"
url: "https://username.github.io"  # Change to your actual GitHub Pages URL

# Build settings
theme: minima  # Use any supported theme, e.g., jekyll-theme-cayman
markdown: kramdown
permalink: pretty

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
